version: '3.8'
services:

  db:
    restart: always
    container_name: db
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    restart: always
    image: awdie/backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env

  frontend:
    restart: always
    image: awdie/frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    restart: always
    image: nginx:1.21.3-alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
      - frontend

volumes:
  static_value:
  media_value:
  db_data: